spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: lending-service
            uri: lb://mkopo.light
            predicates:
              - Path=/mkopo/**

          - id: security-service
            uri: lb://security-service
            predicates:
              - Path=/security/**

          - id: notification-service
            uri: lb://notifications
            predicates:
              - Path=/notifications/**

          - id: lending-swagger
            uri: lb://mkopo.light
            predicates:
              - Path=/lending/swagger-ui.html, /lending/swagger-ui/**, /lending/api-docs, /lending/api-docs/**
            filters:
              - RewritePath=/lending/(?<segment>.*), /${segment}

          - id: security-swagger
            uri: lb://security-service
            predicates:
              - Path=/security-docs/swagger-ui.html, /security-docs/swagger-ui/**, /security-docs/api-docs, /security-docs/api-docs/**
            filters:
              - RewritePath=/security-docs/(?<segment>.*), /${segment}

          - id: notification-swagger
            uri: lb://notifications
            predicates:
              - Path=/notification-docs/swagger-ui.html, /notification-docs/swagger-ui/**, /notification-docs/api-docs, /notification-docs/api-docs/**
            filters:
              - RewritePath=/notification-docs/(?<segment>.*), /${segment}

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Lending Service
        url: /lending/api-docs
      - name: Security Service
        url: /security-docs/api-docs
      - name: Notification Service
        url: /notification-docs/api-docs
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
